import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputbox: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: 250,
    height: 50,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    marginBottom: '5%',
  },
  textinput: {
    width: 200,
    height: 40,
  },
  loginButton: {
    width: 150,
    height: 35,
    borderRadius: 8,
    backgroundColor: '#6495ed',
    marginTop: '5%',
    marginBottom: '3%',
  },
  registerButton1: {
    width: 150,
    height: 35,
    borderRadius: 8,
    backgroundColor: '#6495ed',
    marginBottom: '3%',
  },
  registerButton2: {
    width: 150,
    height: 35,
    borderRadius: 8,
    backgroundColor: '#66cdaa',
    marginTop: '5%',
    marginBottom: '3%',
  },
  loginButtonText: {
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: '5%',
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  textAttr: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: '4%',
  },
  currentUser: {
    alignSelf: 'flex-end',
    marginTop: '13%',
    marginRight: '5%',
    position: 'absolute',
    fontWeight: '500',
  },
  date: {
    alignSelf: 'flex-end',
    marginTop: '14%',
    marginRight: '9%',
    position: 'absolute',
    fontWeight: '500',
  },
  addButton: {
    width: 100,
    height: 33,
    borderRadius: 8,
    backgroundColor: '#6495ed',
    marginTop: '10%',
  },
  showButton: {
    width: 30,
    height: 18,
    borderRadius: 2,
    marginTop: '4%',
    fontWeight: '800',
    backgroundColor: '#dcdcdc',
    flex: 1.5,
  },
  showText: {
    justifyContent: 'center',
    alignSelf: 'center',
    fontSize: 11,
    fontWeight: '600',
  },
  balanceText: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: '20%',
    flex: 4,
  },
  urlInputBox: {
    alignItems: 'center',
    width: 320,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    marginTop: '30%',
    justifyContent: 'center',
  },
  urlInputText: {
    width: 280,
    height: 30,
  },
  infoText: {
    alignSelf: 'auto',
    fontWeight: '600',
    marginLeft: '7%',
    marginRight: '7%',
    fontSize: 20,
    marginBottom: '5%',
  },
  backButton: {
    width: 50,
    height: 50,
    borderRadius: 20,
    backgroundColor: '#f0e68c',
  },
  webLoading: {
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    position: 'absolute',
  },
  productImage: {
    width: 220,
    height: 220,
    marginBottom: '3%',
    alignSelf: 'center',
    resizeMode: 'contain',
  },
  reset: {
    position: 'absolute',
    bottom: 0,
    alignSelf: 'flex-end',
    marginRight: '20%',
    marginBottom: '2%',
    // backgroundColor: '#dcdcdc',
  },
  chartTitle: {
    marginLeft: '8%',
    fontWeight: '600',
    fontSize: 18,
  },
  share: {
    position: 'absolute',
    bottom: 0,
    height: 15,
    alignSelf: 'flex-end',
    marginRight: '20%',
    marginBottom: '5%',
    borderRadius: 8,
    backgroundColor: '#add8e6',
  },
  chartLabel: {
    width: 200,
    height: 30,
    borderRadius: 8,
    marginBottom: '2%',
    backgroundColor: '#dcdcdc',
  },
  chartText: {
    fontWeight: '600',
    fontSize: 16,
    alignSelf: 'center',
    marginTop: '2%',
  },
  goalButton: {
    width: 120,
    height: 33,
    borderRadius: 8,
    backgroundColor: '#6495ed',
    marginTop: '10%',
    marginRight: '5%',
  },
  profileTab: {
    flexDirection: 'row',
    marginTop: '5%',
    marginBottom: '10%',
  },
  goalInputBox: {
    alignItems: 'center',
    width: 300,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    marginTop: '5%',
    justifyContent: 'center',
  },
  statusText: {
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: '3%',
    color: '#696969',
  },
  categoryTab: {
    width: 400,
    height: 60,
    flexDirection: 'row',
    marginTop: '2%',
    backgroundColor: '#ecf3f5',
  },
  categoryText: {
    fontSize: 18,
    fontWeight: '600',
    alignSelf: 'center',
    marginLeft: '10%',
    flex: 6,
  },
  addText: {
    fontSize: 16,
    fontWeight: '500',
    alignSelf: 'center',
    flex: 2,
    color: '#696969',
    textDecorationLine: 'underline',
  },
});
