import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputbox: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: 250,
    height: 50,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    marginBottom: '5%',
  },
  textinput: {
    width: 200,
    height: 40,
  },
  loginButton: {
    width: 150,
    height: 35,
    borderRadius: 8,
    backgroundColor: '#6495ed',
    marginTop: '5%',
    marginBottom: '3%',
  },
  registerButton1: {
    width: 150,
    height: 35,
    borderRadius: 8,
    backgroundColor: '#6495ed',
    marginBottom: '3%',
  },
  registerButton2: {
    width: 150,
    height: 35,
    borderRadius: 8,
    backgroundColor: '#66cdaa',
    marginTop: '5%',
    marginBottom: '3%',
  },
  loginButtonText: {
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: '5%',
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  textAttr: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: '5%',
  },
  currentUser: {
    alignSelf: 'flex-end',
    marginTop: '13%',
    marginRight: '5%',
    position: 'absolute',
    fontWeight: '500',
  },
  date: {
    alignSelf: 'flex-end',
    marginTop: '14%',
    marginRight: '9%',
    position: 'absolute',
    fontWeight: '500',
  },
  addButton: {
    width: 100,
    height: 33,
    borderRadius: 8,
    backgroundColor: '#6495ed',
    marginTop: '15%',
  },
  showButton: {
    width: 30,
    height: 18,
    borderRadius: 2,
    marginTop: '4%',
    fontWeight: '800',
    backgroundColor: '#dcdcdc',
    flex: 1.5,
  },
  showText: {
    justifyContent: 'center',
    alignSelf: 'center',
    fontSize: 11,
    fontWeight: '600',
  },
  balanceText: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: '20%',
    flex: 4,
  },
  logout: {

  },
  urlInputBox: {
    alignItems: 'center',
    width: 320,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    marginTop: '30%',
    justifyContent: 'center',
  },
  urlInputText: {
    width: 280,
    height: 30,
  },
  infoText: {
    alignSelf: 'auto',
    fontWeight: '600',
    marginLeft: '7%',
    marginRight: '7%',
    fontSize: 20,
    marginBottom: '5%',
  },
  backButton: {
    width: 50,
    height: 50,
    borderRadius: 20,
    backgroundColor: '#f0e68c',
  },
  webLoading: {
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    position: 'absolute',
  },
  productImage: {
    width: 220,
    height: 220,
    marginBottom: '3%',
    alignSelf: 'center',
    resizeMode: 'contain',
  },
});
